### ISSUE TITLE
Corrupt line

### ISSUE THREAD

**Issue by tnusser** [fhamborg/NewsWCL50#1]
https://github.com/fhamborg/NewsWCL50/blob/888677e3f79567132609582def8cfc54bb7d7e2a/Annotations.csv#L7919
https://github.com/fhamborg/NewsWCL50/blob/888677e3f79567132609582def8cfc54bb7d7e2a/Annotations.csv#L7920
https://github.com/fhamborg/NewsWCL50/blob/888677e3f79567132609582def8cfc54bb7d7e2a/Annotations.csv#L7921

Need to be joined

**Comment by fhamborg** [comment]
Thanks for the issue, we are looking into it

**Comment by anastasia-zhukova** [comment]
The coded phrase starts with the middle of the word, and this word does not exist among the tokens and, therefore, the entire phrase was marked as missing.

**Comment by anastasia-zhukova** [comment]
But I think, it is a coding error: the coded element is just over too big.
![2019-03-13_15-52-00](https://user-images.githubusercontent.com/6137243/54288666-20e1c500-45a8-11e9-8f81-649a99da819c.png)

**Comment by fhamborg** [comment]
fixed
