### ISSUE TITLE
Small typo - 'IRn' should be fully capitalized

### ISSUE THREAD

**Issue by tnusser** [fhamborg/NewsWCL50#10]
https://github.com/fhamborg/NewsWCL50/blob/dbffe441e7022b26609ae9cd1dde498672274f2b/Annotations.csv#L8057

**Comment by fhamborg** [comment]
i guess we can close this, since it has probably been addressed in v2, @anastasia-zhukova ?

**Comment by anastasia-zhukova** [comment]
Yes, this was fixed
