### ISSUE TITLE
Target is missing

### ISSUE THREAD

**Issue by tnusser** [fhamborg/NewsWCL50#2]
Target missing for the following rows:

['PROPERTY', 'Other', 'a supposed encounter', '', '1', 'L', '21.0', '23.0', '21', '31.0']
['PROPERTY', 'Other', 'reportedly lying to investigators', '', '1', 'L', '11.0', '14.0', '35', '52.0']
['PROPERTY', 'Other', 'purportedly describing', '', '1', 'M', '33.0', '34.0', '4', '6.0']
['PROPERTY', 'Other', 'will join', '', '2', 'LL', '19.0', '20.0', '8', '9.0']
['PROPERTY', 'Confidence', "exactly what we're doing today", '', '3', 'M', '14.0', '19.0', '7', '11.0']
['PROPERTY', 'Power', "exactly what we're doing today", '', '3', 'M', '14.0', '19.0', '7', '11.0']
['PROPERTY', 'Other', 'alleges', '', '3', 'M', '3.0', '3.0', '16', '25.0']
['PROPERTY', 'Other', 'according to', '', '4', 'LL', '', '', '38', '']
['PROPERTY', 'Power', 'has already been accomplished', '', '4', 'L', '25.0', '28.0', '20', '45.0']
['PROPERTY', 'Affection', 'expressed solidarity', '', '9', 'M', '15.0', '16.0', '6', '7.0']

**Comment by anastasia-zhukova** [comment]
![2019-03-13_15-28-35](https://user-images.githubusercontent.com/6137243/54286742-b1b6a180-45a4-11e9-8f5c-bc6ac3b20a6f.png)
The target is missing in the original MAXQDA files.

**Comment by fhamborg** [comment]
Alright, thanks for opening the issue @Nusserle and thanks for looking into it @Anastasu6ka. I will fix the issue in the mk18 files.

**Comment by fhamborg** [comment]
fixed
