### ISSUE TITLE
do some target concept codings have a target themselves?

### ISSUE THREAD

**Issue by fhamborg** [fhamborg/NewsWCL50#7]

**Comment by anastasia-zhukova** [comment]
No, why? Six target concepts had some target concepts as well(most likely because of misclicking on the annotation in maxqda) but I fixed that. Have you found smth else?

**Comment by anastasia-zhukova** [comment]
![2019-04-12_14-32-34](https://user-images.githubusercontent.com/6137243/56134499-fe6c0e80-5f8e-11e9-8fba-10757e4ac5c2.png)
These are already fixed in the new file.

**Comment by fhamborg** [comment]
@anastasia-zhukova sorry, forgot to self assign me. looks like the ones i found were the ones you just posted.
