### ISSUE TITLE
have one target concept in a frame property phrase, always

### ISSUE THREAD

**Issue by fhamborg** [fhamborg/NewsWCL50#8]
Currently, some frame property phrases (i.e., rows in the annotations.csv) contain multiple target concepts, e.g., "Trump; Putin". Normalize this, by adding for each target concept (if multiple) of a frame property phrase (in the mx18) a single row.

**Comment by anastasia-zhukova** [comment]
I don’t understand a task. One row = one comment note? But mx18 doesn’t support more than one comment note. Add multiple codes of this preperty and add for each a separate target concept could lead to many mistakes (see problems with typos in comments). The easiest way is to have multiple target concepts as they are and adjust the parsing script.

**Comment by fhamborg** [comment]
> The easiest way is to have multiple target concepts as they are and adjust the parsing script.

Yup, that's exactly what this issue is about :-)
